version: '3'

services:
  medquick-backend:
    build: ./
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: file:./dev.db
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
